language: node_js

services:
  - docker

# build the docker container
before_install:
  - docker build -t amingilani/worklark-slack-app -t registry.heroku.com/$HEROKU_PRODUCTION_APP_NAME/worker .

# deploy the docker container
script:
  - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
  - docker push registry.heroku.com/$HEROKU_PRODUCTION_APP_NAME/worker
