language: node_js

services:
  - docker


before_install:
  - docker build -t amingilani/worklark-slack-app . # build the docker container

script:
  - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
  - docker tag amingilani/worklark-slack-app registry.heroku.com/worklark-slack-app-1203/worker
  - docker push registry.heroku.com/worklark-slack-app-1203/worker
